### ISSUE TITLE
Add imagemagick to php 8 dockerfile

### ISSUE THREAD

**Issue by delboy1978uk** [delboy1978uk/dockerhub#2]

**Comment by wmerfalen** [comment]
This might be the right way, though I haven't confirmed locally. 
https://hub.docker.com/r/amsdard/php

**Comment by delboy1978uk** [comment]
I know how to do it, when i released this imagick wasnt ready for it but as of early this year it works again so i just need to add it in

**Comment by delboy1978uk** [comment]
done and released as v1.1.0
